import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});
const geistAxifoma = localFont({
  src: "./fonts/GeistAxifoma.ttf",
  variable: "--font-geist-axifoma",
  weight: "100 900 800",
});
const geistAxifomabold = localFont({
  src: "./fonts/GeistAxifoma.ttf",
  variable: "--font-geist-axifoma-bold",
  weight: "800",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${geistAxifoma.variable} ${geistAxifomabold.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
